<a href="https://colab.research.google.com/github/chalapathi444/algorithms-in-tensorflow/blob/master/tensorflowdatasetlearningpath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%tensorflow_version 2.x

In [0]:
import tensorflow as tf
import numpy as np

In [21]:
data_set = tf.data.Dataset.from_tensor_slices([1,2,3])
for element in data_set:
  print(element)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [22]:
data_set2 = data_set.map(lambda x:x*x)
for element in data_set2:
  print(element)


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [23]:
data_set3 = tf.data.Dataset.range(100)
def func(data):
  return data.filter(lambda x: x<5)
data_set4 = data_set3.apply(func)
for element in data_set4.as_numpy_iterator():
  print(element)

0
1
2
3
4


In [24]:
data_set4 = tf.data.Dataset.range(8)
data_set_with_batch = data_set4.batch(3)
for i in data_set_with_batch:
  print(i)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)
tf.Tensor([6 7], shape=(2,), dtype=int64)


In [25]:
data_set_with_batch_rem_no = data_set4.batch(3,drop_remainder = True)
for i in data_set_with_batch_rem_no:
  print(i)

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([3 4 5], shape=(3,), dtype=int64)


In [0]:
a = tf.data.Dataset.from_tensor_slices([[[1,2,3]],[[4,5,6]]])
b = tf.data.Dataset.from_tensor_slices([1,0])
c = tf.data.Dataset.zip((a,b))

In [27]:
for i in c:
  print(i)

(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)


In [28]:
dataset1 = tf.data.Dataset.range(8)
dataset2 = dataset1.take(4)
dataset1 = dataset1.skip(4)
#print(list(dataset1.as_numpy_iterator()))
dataset3 = dataset1.take(4)
for i in dataset2.as_numpy_iterator():
  print(i)
for j in dataset3.as_numpy_iterator():
  print(j)

0
1
2
3
4
5
6
7
